// ADRIX AND NEV COMMANDER DECK
const commanderDeck = [
    { name: "Adrix and Nev, Twincasters", set: "MKC", amount: 1 },
    { name: "Arcane Signet", set: "M3C", amount: 1 },
    { name: "Avenger of Zendikar", set: "M3C", amount: 1 },
    { name: "Biomass Mutation", set: "C21", amount: 1 },
    { name: "Body of Research", set: "STX", amount: 1 },
    { name: "Breeding Pool", set: "RNA", amount: 1 },
    { name: "Coiling Oracle", set: "BLC", amount: 1 },
    { name: "Combine Chrysalis", set: "MOC", amount: 1 },
    { name: "Command Tower", set: "M3C", amount: 1 },
    { name: "Cultivate", set: "STA", amount: 1 },
    { name: "Curse of the Swine", set: "M3C", amount: 1 },
    { name: "Desolation Twin", set: "C21", amount: 1 },
    { name: "Doppelgang", set: "MKM", amount: 1 },
    { name: "Double Major", set: "STX", amount: 1 },
    { name: "Druid's Deliverance", set: "MM3", amount: 1 },
    { name: "End-Raze Forerunners", set: "BLC", amount: 1 },
    { name: "Esix, Fractal Bloom", set: "MKC", amount: 1 },
    { name: "Explore", set: "OTC", amount: 1 },
    { name: "Explosive Vegetation", set: "DTK", amount: 1 },
    { name: "Forest", set: "WOE", amount: 16 },
    { name: "Fountainport", set: "BLB", amount: 1, foil: true },
    { name: "Full Flowering", set: "C19", amount: 1 },
    { name: "Garruk's Uprising", set: "WOT", amount: 1 },
    { name: "Giant Adephage", set: "CLU", amount: 1 },
    { name: "Growth Spasm", set: "MIC", amount: 1 },
    { name: "Gruff Triplets", set: "WOE", amount: 1 },
    { name: "Hornet Nest", set: "C21", amount: 1 },
    { name: "Hornet Queen", set: "MKC", amount: 1 },
    { name: "Island", set: "CMR", amount: 15 },
    { name: "Junk Winder", set: "BLC", amount: 1 },
    { name: "Kazandu Tuskcaller", set: "C21", amount: 1 },
    { name: "Kiora's Follower", set: "LCC", amount: 1 },
    { name: "Kodama's Reach", set: "CMM", amount: 1 },
    { name: "Krosan Grip", set: "STA", amount: 1 },
    { name: "Lightning Greaves", set: "OTC", amount: 1 },
    { name: "Llanowar Elves", set: "M19", amount: 1 },
    { name: "Mitotic Slime", set: "NCC", amount: 1 },
    { name: "Murkfiend Liege", set: "2X2", amount: 1 },
    { name: "Myr Battlesphere", set: "M3C", amount: 1 },
    { name: "Negate", set: "OGW", amount: 1 },
    { name: "Novijen, Heart of Progress", set: "C21", amount: 1 },
    { name: "Oko, Thief of Crowns", set: "OTP", amount: 1 },
    { name: "Peregrin Took", set: "LTR", amount: 1 },
    { name: "Propagator Drone", set: "MH3", amount: 1 },
    { name: "Prophet of Kruphix", set: "THS", amount: 1 },
    { name: "Quandrix Apprentice", set: "STX", amount: 1 },
    { name: "Quandrix Command", set: "LCC", amount: 1 },
    { name: "Rampaging Baloths", set: "BLC", amount: 1 },
    { name: "Rampant Growth", set: "BLC", amount: 1 },
    { name: "Reality Shift", set: "WOC", amount: 1 },
    { name: "Reef Worm", set: "MH3", amount: 1 },
    { name: "Sandwurm Convergence", set: "CMM", amount: 1 },
    { name: "Saproling Symbiosis", set: "DMR", amount: 1 },
    { name: "Scute Swarm", set: "ZNR", amount: 1 },
    { name: "Simic Charm", set: "CMR", amount: 1 },
    { name: "Simic Growth Chamber", set: "M3C", amount: 1 },
    { name: "Simic Signet", set: "RVR", amount: 1 },
    { name: "Sol Ring", set: "M3C", amount: 1 },
    { name: "Swiftfoot Boots", set: "BLC", amount: 1 },
    { name: "Temple of Mystery", set: "BLC", amount: 1 },
    { name: "Temple of the False God", set: "OTC", amount: 1 },
    { name: "Terastodon", set: "M3C", amount: 1 },
    { name: "Thought Vessel", set: "BLC", amount: 1 },
    { name: "Tireless Tracker", set: "MKC", amount: 1 },
    { name: "Tyvar's Stand", set: "ONE", amount: 1 },
    { name: "Unsummon", set: "HOU", amount: 1 },
    { name: "Vanguard Suppressor", set: "40K", amount: 1 },
    { name: "Volo, Guide to Monsters", set: "AFR", amount: 1 },
    { name: "Watchful Radstag", set: "PIP", amount: 1 },
    { name: "Zendikar's Roil", set: "ZNC", amount: 1 },
    { name: "Zimone, Quandrix Prodigy", set: "STX", amount: 1 }
];

// SIDEBOARD
const sideboard = [
    { name: "Adrix and Nev, Twincasters", set: "MKC", amount: 1 },
    { name: "Beast", set: "TBLC", amount: 1 },
    { name: "Copy", set: "TLCI", amount: 3 },
    { name: "Eldrazi", set: "TBLC", amount: 1 },
    { name: "Eldrazi Spawn", set: "TMH3", amount: 1 },
    { name: "Elephant", set: "TMH1", amount: 1 },
    { name: "Food", set: "TLTR", amount: 1 },
    { name: "Insect", set: "TDMU", amount: 1 },
    { name: "Phyrexian Beast", set: "TONE", amount: 1 },
    { name: "Treasure", set: "TSNC", amount: 1 }
];

// MAYBEBOARD
const maybeBoard = [
    { name: "Perplexing Test", set: "BLC", amount: 1 }
];
