// EDGAR MARKOV COMMANDER DECK
const commanderDeck = [
    { name: "Edgar Markov", set: "C17", foil: true, commander: true },
    { name: "Anowon, the Ruin Sage", set: "VOC" },
    { name: "Baron Bertram Graywater", set: "OTJ" },
    { name: "Bartolomé del Presidio", set: "LCI" },
    { name: "Blade of the Bloodchief", set: "C17" },
    { name: "Blind Obedience", set: "RVR" },
    { name: "Blood Artist", set: "C17" },
    { name: "Blood Baron of Vizkopa", set: "C17" },
    { name: "Blood Crypt", set: "RVR" },
    { name: "Bloodfell Caves", set: "C19" },
    { name: "Bloodline Necromancer", set: "VOC" },
    { name: "Bloodstained Mire", set: "MH3" },
    { name: "Bojuka Bog", set: "BLC" },
    { name: "Boros Signet", set: "CMM" },
    { name: "Butcher of Malakir", set: "C17" },
    { name: "Captivating Vampire", set: "C17" },
    { name: "Cast Down", set: "PMEI", foil: true },
    { name: "Cavern of Souls", set: "ZNE" },
    { name: "Charismatic Conqueror", set: "LCC" },
    { name: "City of Brass", set: "6ED" },
    { name: "Command Tower", set: "C17" },
    { name: "Consuming Vapors", set: "AFC" },
    { name: "Crackling Doom", set: "2X2" },
    { name: "Creeping Bloodsucker", set: "J22" },
    { name: "Cruel Celebrant", set: "LCC" },
    { name: "Disrupt Decorum", set: "MKC" },
    { name: "Door of Destinies", set: "C17" },
    { name: "Dragonskull Summit", set: "DMC" },
    { name: "Drana, Kalastria Bloodchief", set: "C17" },
    { name: "Drana, Liberator of Malakir", set: "LCC" },
    { name: "Dusk Legion Zealot", set: "RIX", foil: true },
    { name: "Edgar, Charmed Groom // Edgar Markov's Coffin", set: "VOW" },
    { name: "Elesh Norn, Mother of Machines", set: "ONE" },
    { name: "Exotic Orchard", set: "M3C" },
    { name: "Exquisite Blood", set: "SLD" },
    { name: "Farewell", set: "WHO" },
    { name: "Fell the Mighty", set: "MKC" },
    { name: "Go for the Throat", set: "2X2" },
    { name: "Godless Shrine", set: "GPT" },
    { name: "Haunted Ridge", set: "MID" },
    { name: "Isolated Chapel", set: "ISD" },
    { name: "Kheru Mind-Eater", set: "C17" },
    { name: "Kindred Boon", set: "C17" },
    { name: "Kindred Charge", set: "C17" },
    { name: "Legion Lieutenant", set: "RIX" },
    { name: "Luxury Suite", set: "ZNE" },
    { name: "Malakir Bloodwitch", set: "C17" },
    { name: "Markov Baron", set: "MAT" },
    { name: "Marsh Flats", set: "ZNE" },
    { name: "Merciless Eviction", set: "C17" },
    { name: "Mortify", set: "C18" },
    { name: "Mountain", set: "LTR" },
    { name: "New Blood", set: "C17" },
    { name: "Nomad Outpost", set: "C17" },
    { name: "Olivia's Wrath", set: "LCC" },
    { name: "Opal Palace", set: "M3C" },
    { name: "Orzhov Signet", set: "OTC" },
    { name: "Path of Ancestry", set: "C17" },
    { name: "Patron of the Vein", set: "C17" },
    { name: "Plains", set: "CMM" },
    { name: "Rakdos Signet", set: "OTC" },
    { name: "Rakish Heir", set: "C17" },
    { name: "Read the Bones", set: "CMM" },
    { name: "Return to Dust", set: "CMM" },
    { name: "Ruthless Lawbringer", set: "OTJ" },
    { name: "Sanctum Seeker", set: "LCC" },
    { name: "Sangromancer", set: "C21" },
    { name: "Sanguine Bond", set: "WOT" },
    { name: "Savai Triome", set: "IKO" },
    { name: "Scoured Barrens", set: "M20" },
    { name: "Secluded Courtyard", set: "M3C" },
    { name: "Shattered Landscape", set: "MH3" },
    { name: "Shattered Sanctum", set: "VOW" },
    { name: "Skullclamp", set: "C17" },
    { name: "Smoldering Marsh", set: "EXP", foil: true },
    { name: "Sol Ring", set: "M3C" },
    { name: "Sorin, Imperious Bloodlord", set: "M20" },
    { name: "Stromkirk Captain", set: "C17" },
    { name: "Swamp", set: "CMM", count: 9 },
    { name: "Swords to Plowshares", set: "BBD" },
    { name: "Teferi's Protection", set: "2X2" },
    { name: "Tithe Drinker", set: "C17" },
    { name: "Umezawa's Jitte", set: "PGPX", foil: true },
    { name: "Vampire Nighthawk", set: "C17" },
    { name: "Vampire Socialite", set: "MID" },
    { name: "Vampire of the Dire Moon", set: "M20" },
    { name: "Vampiric Rites", set: "WOT" },
    { name: "Vault of Champions", set: "CMM" },
    { name: "Vindicate", set: "EMA" },
    { name: "Vito, Thorn of the Dusk Rose", set: "M21" },
    { name: "Voldaren Estate", set: "VOW", foil: true },
    { name: "Welcoming Vampire", set: "MKC" },
    { name: "Worn Powerstone", set: "MH3" }
];

// MAYBEBOARD
const maybeBoard = [
    { name: "Anje, Maid of Dishonor", set: "VOW" },
    { name: "Black Market", set: "C17" },
    { name: "Bloodlord of Vaasgoth", set: "C17" },
    { name: "Damnable Pact", set: "C17" },
    { name: "Dark Impostor", set: "C17" },
    { name: "Evolving Wilds", set: "C17" },
    { name: "Falkenrath Noble", set: "C17" },
    { name: "Orzhov Basilica", set: "C17" },
    { name: "Sorin, Lord of Innistrad", set: "DKA" },
    { name: "Terramorphic Expanse", set: "C17" }
];
