// INALLA COMMANDER DECK
const inallaCommanderDeck = [
    { name: "Inalla, Archmage Ritualist", set: "C17", amount: 1, foil: true },
    { name: "Adeliz, the Cinder Wind", set: "DOM", amount: 1 },
    { name: "Arcane Signet", set: "M3C", amount: 1 },
    { name: "Arcanis the Omnipotent", set: "DMR", amount: 1 },
    { name: "Azami, Lady of Scrolls", set: "CMM", amount: 1 },
    { name: "Basalt Ravager", set: "KHM", amount: 1 },
    { name: "Bedevil", set: "OTP", amount: 1 },
    { name: "Black Sun's Twilight", set: "ONE", amount: 1 },
    { name: "Bloodline Necromancer", set: "VOC", amount: 1 },
    { name: "Blur", set: "CLB", amount: 1 },
    { name: "Choked Estuary", set: "MKC", amount: 1 },
    { name: "Cloudkin Seer", set: "CLU", amount: 1 },
    { name: "Command Tower", set: "M3C", amount: 1 },
    { name: "Corpse Augur", set: "CMM", amount: 1 },
    { name: "Counterspell", set: "DMR", amount: 1 },
    { name: "Crosis's Charm", set: "PLS", amount: 1 },
    { name: "Crumbling Necropolis", set: "NCC", amount: 1 },
    { name: "Cyclone Summoner", set: "KHM", amount: 1 },
    { name: "Darkwater Catacombs", set: "CLB", amount: 1 },
    { name: "Dimir Locket", set: "ZNC", amount: 1 },
    { name: "Dimir Signet", set: "CLU", amount: 1 },
    { name: "Exclusion Mage", set: "M19", amount: 1 },
    { name: "Fabled Passage", set: "BLB", amount: 1 },
    { name: "Feed the Swarm", set: "OTC", amount: 1 },
    { name: "Fire Diamond", set: "CLB", amount: 1 },
    { name: "Foreboding Statue // Forsaken Thresher", set: "VOW", amount: 1 },
    { name: "Frantic Search", set: "WOC", amount: 1 },
    { name: "Frostboil Snarl", set: "M3C", amount: 1 },
    { name: "Ghostly Flicker", set: "CMM", amount: 1 },
    { name: "Goblin Electromancer", set: "OTC", amount: 1 },
    { name: "Impact Tremors", set: "WOT", amount: 1 },
    { name: "Island", set: "WOE", amount: 11 },
    { name: "Izzet Chronarch", set: "C17", amount: 1 },
    { name: "Izzet Locket", set: "C19", amount: 1 },
    { name: "Izzet Signet", set: "BLC", amount: 1 },
    { name: "Kefnet's Monument", set: "AKH", amount: 1 },
    { name: "Maestros Theater", set: "SNC", amount: 1 },
    { name: "Merchant of Secrets", set: "C17", amount: 1 },
    { name: "Mind Stone", set: "CLB", amount: 1 },
    { name: "Mountain", set: "KLD", amount: 6 },
    { name: "Naban, Dean of Iteration", set: "DOM", amount: 1 },
    { name: "Naru Meha, Master Wizard", set: "C21", amount: 1 },
    { name: "Nightscape Familiar", set: "DMR", amount: 1 },
    { name: "Niv-Mizzet, Parun", set: "OTC", amount: 1 },
    { name: "Niv-Mizzet, the Firemind", set: "C20", amount: 1 },
    { name: "Overwhelmed Apprentice", set: "ELD", amount: 1 },
    { name: "Peregrine Drake", set: "DMR", amount: 1 },
    { name: "Portal Mage", set: "CMM", amount: 1 },
    { name: "Prismatic Lens", set: "CMM", amount: 1 },
    { name: "Puppeteer Clique", set: "WOC", amount: 1 },
    { name: "Reality Shift", set: "WOC", amount: 1 },
    { name: "Riptide Laboratory", set: "MH2", amount: 1 },
    { name: "Riverwise Augur", set: "AFC", amount: 1 },
    { name: "Sea Gate Oracle", set: "KHC", amount: 1 },
    { name: "Sedraxis Alchemist", set: "CON", amount: 1 },
    { name: "Seething Landscape", set: "MH3", amount: 1 },
    { name: "Serendib Sorcerer", set: "C17", amount: 1 },
    { name: "Serum Visionary", set: "MH3", amount: 1 },
    { name: "Shadowmage Infiltrator", set: "NCC", amount: 1 },
    { name: "Sky Diamond", set: "CLB", amount: 1 },
    { name: "Sol Ring", set: "M3C", amount: 1 },
    { name: "Step Through", set: "MH2", amount: 1 },
    { name: "Stern Proctor", set: "USG", amount: 1 },
    { name: "Stonybrook Banneret", set: "LCC", amount: 1 },
    { name: "Sunken Hollow", set: "OTC", amount: 1 },
    { name: "Swamp", set: "ELD", amount: 6 },
    { name: "Swiftfoot Boots", set: "BLC", amount: 1 },
    { name: "Trinket Mage", set: "DDF", amount: 1 },
    { name: "Unearth", set: "2X2", amount: 1 },
    { name: "Unwind", set: "DOM", amount: 1 },
    { name: "Valley Floodcaller", set: "BLB", amount: 1 },
    { name: "Victimize", set: "MH3", amount: 1 },
    { name: "Village Rites", set: "M21", amount: 1 },
    { name: "Vindictive Lich", set: "CMM", amount: 1 },
    { name: "Warstorm Surge", set: "CLB", amount: 1 },
    { name: "Watcher for Tomorrow", set: "MH1", amount: 1 },
    { name: "Wayfarer's Bauble", set: "M3C", amount: 1 },
    { name: "Winter Eladrin", set: "CLB", amount: 1 },
    { name: "Wizard's Retort", set: "DOM", amount: 1 },
    { name: "Worn Powerstone", set: "MH3", amount: 1 }
];
